# Generated by Django 5.1.4 on 2025-01-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
